# Generated by Django 3.0.5 on 2020-09-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('patient_name', models.CharField(max_length=128)),
                ('appointment_at', models.DateTimeField()),
                ('patient_email', models.CharField(max_length=128)),
            ],
        ),
    ]
