# Generated by Django 3.0.5 on 2020-09-19 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
