# Generated by Django 3.0.5 on 2020-09-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200919_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='flight_airline',
            field=models.CharField(default='a', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_number',
            field=models.CharField(default='a', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_origin',
            field=models.CharField(default='a', max_length=64),
            preserve_default=False,
        ),
    ]
